name: valorant_wiki
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  responsive_sizer: ^3.3.0+1
  dynamic_height_grid_view: ^0.0.4
  stroke_text: ^0.0.2
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  transparent_image: ^2.0.1
  path_provider: ^2.0.5
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/agents.png
   - assets/images/gunbuddies.png
   - assets/images/maps.png
   - assets/images/cards.png
   - assets/images/sprays.png
   - assets/images/ranks.png
   - assets/images/weapons.png
  fonts:
    - family: BowlbyOneSC
      fonts:
        - asset: assets/fonts/BowlbyOneSC-Regular.ttf
        